[package]
name = "moosync"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta.10", features = [] }

[dependencies]
macros = { path = "./macros" }
database = { path = "./database" }
types = { path = "./types" }
youtube = { path = "./youtube" }
preferences = { path = "./preferences" }
file_scanner = { path = "./file_scanner" }
librespot = { path = "./librespot" }
themes = { path = "./themes" }
mpris = { path = "./mpris" }
lyrics = { path = "./lyrics" }
extensions = { path = "./extensions" }
tauri = { version = "2.0.0-beta.13", features = [
    "protocol-asset",
    "devtools",
    "default",
] }
tauri-plugin-deep-link = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-devtools = { git = "https://github.com/crabnebula-dev/devtools" }
webkit2gtk = "2.0.1"
open = "5.0.1"
thiserror = "1.0.57"
uuid = { version = "1.7.0", features = ["std", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = { version = "0.14.0", default-features = false, features = [
    "xdg-portal",
    "async-std",
] }

[rfd.features]


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
strip = "symbols"

[profile.dev]
# debug = 0
opt-level = 0
lto = false
incremental = true
