[package]
name = "moosync"
edition = "2021"
version = "0.0.0"
authors = ["you"]
description = "A Tauri App"

[dependencies]
async-trait = "0.1.81"
chrono = "0.4.38"
ctrlc = "3.4.4"
flame = "0.2.2"
flamer = "0.5.0"
futures = "0.3.30"
iso8601 = "0.6.1"
oauth2 = "4.4.2"
open = "5.3.0"
rspotify = "0.13.2"
serde_json = "1.0"
thiserror = "1.0.63"
url = "2.5.2"
webkit2gtk = "2.0.1"

[dependencies.database]
path = "./database"
features = []

[dependencies.extensions]
path = "./extensions"
features = []

[dependencies.file_scanner]
path = "./file_scanner"
features = []

[dependencies.google-youtube3]
version = "5.0.5"
features = []
default-features = false

[dependencies.librespot]
path = "./librespot"
features = []
default-features = false

[dependencies.lyrics]
path = "./lyrics"
features = []

[dependencies.macros]
path = "./macros"
features = []

[dependencies.mpris]
path = "./mpris"
features = []

[dependencies.preferences]
path = "./preferences"
features = []

[dependencies.reqwest]
version = "0.12.5"
features = ["http2", "charset", "macos-system-configuration"]
default-features = false

[dependencies.rfd]
version = "0.14.1"
features = ["ashpd", "async-std", "pollster", "xdg-portal"]
default-features = false

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta.24"
features = ["objc-exception", "http-range", "compression", "common-controls-v6", "protocol-asset", "tauri-runtime-wry", "wry"]
default-features = false

[dependencies.tauri-plugin-deep-link]
git = "https://github.com/tauri-apps/plugins-workspace"
branch = "v2"
features = []

[dependencies.tauri-plugin-devtools]
git = "https://github.com/crabnebula-dev/devtools"
features = []

[dependencies.tauri-plugin-single-instance]
git = "https://github.com/tauri-apps/plugins-workspace"
branch = "v2"
features = []

[dependencies.themes]
path = "./themes"
features = []

[dependencies.types]
path = "./types"
features = []

[dependencies.uuid]
version = "1.10.0"
features = ["std", "v4"]

[dependencies.youtube]
path = "./youtube"
features = []

[build-dependencies.tauri-build]
version = "2.0.0-beta.19"
features = []

[features]
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
required-features = []

[profile.dev]
opt-level = 0
debug = false
lto = false
incremental = true

[profile.dev.package]
