workspace = { members = [
    "database",
    "macros",
    "preferences",
    "types",
    "youtube",
] }

[package]
name = "moosync"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
macros = { path = "./macros" }
database = { path = "./database" }
types = { path = "./types" }
youtube = { path = "./youtube" }
preferences = { path = "./preferences" }
tauri = { version = "2.0.0-beta", features = ["protocol-asset", "devtools"] }
tauri-plugin-deep-link = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
webkit2gtk = "2.0.1"
open = "5.0.1"
thiserror = "1.0.57"
uuid = { version = "1.7.0", features = ["std", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
strip = "symbols"
