[package]
name = "themes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
regex = { default-features = false, version = "1.10.6" }
serde_json = { default-features = false, version = "1.0" }
types = { path = "../types" , default-features = false }
uuid = { default-features = false, version = "1.10.0" }
zip-extensions = { default-features = false, version = "0.8.1" }
tracing = { version = "0.1.40", default-features = false }
