[package]
name = "themes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
regex = { default-features = false, version = "1.11.1" }
serde_json = { default-features = false, version = "1.0" }
types = { path = "../types", default-features = false, features = ["core"] }
uuid = { default-features = false, version = "1.11.0" }
zip = { version = "2.1.1", default-features = false, features = ["deflate"] }
zip-extensions = { default-features = false, version = "0.8.1" }
tracing = { version = "0.1.41", default-features = false }
notify = "7.0.0"
reqwest = "0.12.11"
serde = "1.0.217"
futures = { default-features = false, version = "0.3.31" }
