[package]
name = "themes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
preferences = { path = "../preferences" }
regex = "1.10.3"
regress = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
types = { path = "../types" }
uuid = "1.7.0"
zip = "0.6.6"
zip-extensions = "0.6.2"
