[package]
name = "Moosync-ui"
version = "0.0.0"
edition = "2021"

[features]
mock = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
console_error_panic_hook = "0.1.7"

leptos = { version = "0.6.13", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
stylers = "0.3.2"
types = { path = "src-tauri/types", default-features = false, features = [
    "ui",
] }
uuid = "1.10.0"
chrono = "0.4.38"
leptos-use = "0.10.10"
async-channel = "2.3.1"
tokio = { version = "1.39.2", features = ["rt", "sync"] }
serde_json = "1.0.120"
leptos_router = { version = "0.6.13", features = ["csr"] }
leptos_virtual_scroller = { git = "https://github.com/Ovenoboyo/leptos_virtual_scroller" }
oauth2 = "4.4.2"
async-trait = "0.1.81"
url = "2.5.2"
rspotify = "0.13.2"
web-time = "1.1.0"
futures = "0.3.30"
web-sys = { version = "0.3.69", features = [
    "Window",
    "Document",
    "HtmlElement",
    "Element",
    "CssStyleDeclaration",
] }
regex = "1.10.5"
colors-transform = "0.2.11"
leptos_i18n = { version = "0.3.3" }
pref_gen = { path = "src/pref_gen" }

[workspace]
resolver = "2"
members = [
    "src-tauri",
    "src-tauri/database",
    "src-tauri/extensions",
    "src-tauri/file_scanner",
    "src-tauri/librespot",
    "src-tauri/lyrics",
    "src-tauri/macros",
    "src-tauri/mpris",
    "src-tauri/preferences",
    "src-tauri/themes",
    "src-tauri/types",
    "src-tauri/youtube",
    "src/pref_gen",
]

[package.metadata.leptos-i18n]
default = "en_US"
locales = [
    "af_ZA",
    "ar_SA",
    "ca_ES",
    "cs_CZ",
    "da_DK",
    "de_DE",
    "el_GR",
    "en_US",
    "es_ES",
    "fi_FI",
    "fr_FR",
    "he_IL",
    "hi_IN",
    "hu_HU",
    "it_IT",
    "ja_JP",
    "ko_KR",
    "nl_NL",
    "no_NO",
    "pl_PL",
    "pt_BR",
    "pt_PT",
    "ro_RO",
    "ru_RU",
    "sr_SP",
    "sv_SE",
    "tr_TR",
    "uk_UA",
    "vi_VN",
    "zh_CN",
    "zh_TW",
]

[profile.release]
strip = "symbols"

[profile.dev]
# debug = 0
# opt-level = 0
# lto = false
incremental = true
