[package]
name = "Moosync-ui"
version = "0.0.0"
edition = "2021"

[features]
mock = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
console_error_panic_hook = "0.1.7"

leptos = { version = "0.6.15", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
types = { path = "src-tauri/types", default-features = false, features = [
    "ui",
] }
chrono = "0.4.39"
leptos-use = "0.12.0"
tokio = { version = "1.42.0", features = ["rt", "sync"] }
serde_json = "1.0.133"
leptos_router = { version = "0.6.15", features = ["csr"] }
leptos_virtual_scroller = { git = "https://github.com/Ovenoboyo/leptos_virtual_scroller" }
leptos_context_menu = { git = "https://github.com/Ovenoboyo/leptos_context_menu" }
futures = "0.3.31"
web-sys = { version = "=0.3.70", features = [
    "Window",
    "Document",
    "HtmlElement",
    "Element",
    "CssStyleDeclaration",
] }
regex = "1.11.1"
colors-transform = "0.2.11"
leptos_i18n = { version = "0.3.3" }
pref_gen = { path = "src/pref_gen" }
rand = "0.8.5"
dyn-clone = "1.0.17"
itertools = "0.13.0"
bitcode = { version = "0.6.3" }
indexed_db_futures = "0.5.0"
lazy_static = "1.5.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tauri-invoke-proc = { path = "src-tauri/tauri-invoke-proc" }

[workspace]
resolver = "2"
members = [
    "src-tauri",
    "src-tauri/database",
    "src-tauri/extensions",
    "src-tauri/file_scanner",
    "src-tauri/librespot",
    "src-tauri/lyrics",
    "src-tauri/macros",
    "src-tauri/mpris",
    "src-tauri/preferences",
    "src-tauri/themes",
    "src-tauri/types",
    "src-tauri/youtube",
    "src-tauri/rodio-player",
    "src/pref_gen",
    "src-tauri/tauri-invoke-proc",
]

[package.metadata.leptos-i18n]
default = "en_US"
locales = [
    "af_ZA",
    "ar_SA",
    "ca_ES",
    "cs_CZ",
    "da_DK",
    "de_DE",
    "el_GR",
    "en_US",
    "es_ES",
    "fi_FI",
    "fr_FR",
    "he_IL",
    "hi_IN",
    "hu_HU",
    "it_IT",
    "ja_JP",
    "ko_KR",
    "nl_NL",
    "no_NO",
    "pl_PL",
    "pt_BR",
    "pt_PT",
    "ro_RO",
    "ru_RU",
    "sr_SP",
    "sv_SE",
    "tr_TR",
    "uk_UA",
    "vi_VN",
    "zh_CN",
    "zh_TW",
]


[profile.release]
strip = "symbols"
debug = 0
opt-level = 3
lto = true
incremental = false
codegen-units = 1
