[package]
name = "Moosync-ui"
version = "0.0.0"
edition = "2021"

[features]
mock = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
console_error_panic_hook = "0.1.7"

leptos = { version = "0.6.9", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
stylers = "0.3.2"
types = { path = "src-tauri/types", default-features = false, features = [
    "ui",
] }
uuid = "1.8.0"
chrono = "0.4.37"
leptos-use = "0.10.5"
async-channel = "2.2.0"
tokio = { version = "1.37.0", features = ["rt", "sync"] }
serde_json = "1.0.115"
leptos_router = { version = "0.6.9", features = ["csr"] }
leptos_virtual_scroller = { git = "https://github.com/Ovenoboyo/leptos_virtual_scroller" }

[workspace]
resolver = "2"
members = [
    "src-tauri",
    "src-tauri/database",
    "src-tauri/extensions",
    "src-tauri/file_scanner",
    "src-tauri/librespot",
    "src-tauri/lyrics",
    "src-tauri/macros",
    "src-tauri/mpris",
    "src-tauri/preferences",
    "src-tauri/themes",
    "src-tauri/types",
    "src-tauri/youtube",
]

[profile.release]
strip = "symbols"

[profile.dev]
debug = 0
opt-level = 0
lto = false
incremental = true
