[build]
target = "index.html"

[watch]
ignore = ["src-tauri", "target", "lib", "package"]

[serve]
addresses = ["127.0.0.1"]
port = 1420
open = false
ws_protocol = "ws"

[tools]
wasm_opt = "version_122"
