[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ytdl = { default-features = false, version = "0.7.4", features = [
    "search",
] }
types = { path = "../types" }
serde_json = { default-features = false, version = "1.0.125" }
tokio = "1.39.3"
serde = { default-features = false, version = "1.0.208" }
tracing = { version = "0.1.40", default-features = false }
