[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ytdl = "0.7.3"
database = { path = "../database" }
types = { path = "../types" }
serde_json = "1.0.120"
reqwest = { version = "0.12.5", features = ["json"] }
tokio = "1.39.2"
serde_derive = "1.0.204"
serde = "1.0.204"
regex = "1.10.5"
url = "2.5.2"
