[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ytdl = { git = "https://github.com/Mithronn/rusty_ytdl" }
types = { path = "../types" }
serde_json = { default-features = false, version = "1.0.140" }
tokio = "1.43.0"
serde = { default-features = false, version = "1.0.218" }
tracing = { version = "0.1.41", default-features = false }
