[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ytdl = "0.7.4"
types = { path = "../types" }
serde_json = "1.0.125"
reqwest = { version = "0.12.5", features = ["json"] }
tokio = "1.39.3"
serde_derive = "1.0.208"
serde = "1.0.208"
regex = "1.10.6"
url = "2.5.2"
tracing = { version = "0.1.40", features = ["attributes"] }
