[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ytdl = "0.7.2"
database = { path = "../database" }
types = { path = "../types" }
serde_json = "1.0.117"
reqwest = { version = "0.12.4", features = ["json"] }
tokio = "1.38.0"
serde_derive = "1.0.203"
serde = "1.0.203"
regex = "1.10.5"
url = "2.5.0"
