[package]
name = "extensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
futures = "0.3.30"
interprocess = { version = "2.2.0", features = ["tokio"] }
reqwest = {version = "0.12.4", features = ["stream"]}
serde = "1.0.203"
serde_json = "1.0.117"
tauri = { version = "2.0.0-beta.22" }
types = { path = "../types" }
database = { path = "../database" }
preferences = { path = "../preferences" }
uuid = "1.8.0"
zip = "2.1"
zip-extensions = "0.8"
