[package]
name = "extensions"
edition = "2021"
version = "0.1.0"

[dependencies]
fs_extra = "1.3.0"
futures = "0.3.30"
serde = "1.0.204"
uuid = "1.10.0"
zip = "2.1"
zip-extensions = "0.8"

[dependencies.database]
path = "../database"
features = []

[dependencies.interprocess]
version = "2.2.1"
features = ["tokio"]

[dependencies.preferences]
path = "../preferences"
features = []

[dependencies.reqwest]
version = "0.12.5"
features = ["stream"]

[dependencies.serde_json]
version = "1.0.120"
features = []
default-features = false

[dependencies.tauri]
version = "2.0.0-beta.24"
features = []

[dependencies.types]
path = "../types"
features = []
