[package]
name = "extensions"
edition = "2021"
version = "0.1.0"

[dependencies]
base64 = "0.22.1"
fs_extra = "1.3.0"
futures = "0.3.30"
serde = "1.0.208"
serde_yaml = "0.9.34"
tokio = "1.39.3"
uuid = "1.10.0"
zip = "2.1"
zip-extensions = "0.8"

[dependencies.interprocess]
version = "2.2.1"
features = ["tokio"]

[dependencies.reqwest]
version = "0.12.5"
features = ["stream"]

[dependencies.serde_json]
version = "1.0.125"
features = []
default-features = false

[dependencies.types]
path = "../types"
features = []
