[package]
name = "extensions"
edition = "2021"
version = "0.1.0"

[dependencies]
base64 = { default-features = false, version = "0.22.1" }
fs_extra = "1.3.0"
futures = { default-features = false, version = "0.3.30" }
serde = { default-features = false, version = "1.0.210" }
serde_yaml = "0.9.34"
tokio = "1.40.0"
uuid = { default-features = false, version = "1.10.0" }
zip-extensions = { default-features = false, version = "0.8" }
tracing = { version = "0.1.40", default-features = false }


[dependencies.interprocess]
version = "2.2.1"
features = ["tokio"]

[dependencies.reqwest]
version = "0.12.7"
features = ["stream"]

[dependencies.serde_json]
version = "1.0.128"
features = []
default-features = false

[dependencies.types]
path = "../types"
features = []
