[package]
name = "extensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
futures = "0.3.30"
interprocess = { version = "1.2.1", features = ["tokio"] }
reqwest = "0.11.26"
serde = "1.0.197"
serde_json = "1.0.114"
tauri = { version = "2.0.0-beta.12" }
types = { path = "../types" }
database = { path = "../database" }
preferences = { path = "../preferences" }
uuid = "1.7.0"
zip = "0.6"
zip-extensions = "0.6"
