[package]
name = "librespot"
edition = "2021"
version = "0.1.0"

[dependencies]
quote = "1.0.36"
regex = "1.10.6"
url = "2.5.2"
tracing = { version = "0.1.40", features = ["attributes"] }

[dependencies.futures-util]
version = "0.3.30"
features = []

[dependencies.librespot]
git = "https://github.com/librespot-org/librespot"
branch = "dev"
features = ["default"]

[dependencies.protobuf]
version = "3.5.0"
features = ["bytes"]

[dependencies.reqwest]
version = "0.12.5"
features = ["http2", "default-tls", "macos-system-configuration"]
default-features = false

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.39.3"
features = ["full"]

[dependencies.types]
path = "../types"
features = []
