[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { path = "../macros" }
types = { path = "../types" }
diesel = { version = "2.1.0", features = ["sqlite", "r2d2", "serde_json"] }
diesel_migrations = { features = ["sqlite"], version = "2.1.0" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.7.0", features = ["std", "v4"] }
