[package]
name = "database"
edition = "2021"
version = "0.1.0"

[dependencies]
serde_json = "1.0"

[dependencies.diesel]
version = "2.1.0"
features = ["sqlite", "r2d2", "serde_json"]

[dependencies.diesel_migrations]
version = "2.1.0"
features = ["sqlite"]

[dependencies.macros]
path = "../macros"
features = []

[dependencies.serde]
version = "1.0"
features = ["derive", "serde_derive"]
default-features = false

[dependencies.types]
path = "../types"
features = []

[dependencies.uuid]
version = "1.7.0"
features = ["std", "v4"]
