[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["core"]
core = [
    "dep:souvlaki",
    "dep:rusty_ytdl",
    "dep:tauri",
    "dep:diesel",
    "dep:fast_image_resize",
    "dep:image",
    "dep:lofty",
    "dep:jwalk",
    "dep:librespot",
    "dep:protobuf",
    "dep:zip",
    "dep:fs_extra",
    "dep:oauth2",
    "dep:rspotify",
    "dep:google-youtube3",
]
ui = ["dep:wasm-bindgen", "dep:serde-wasm-bindgen"]

[dependencies]
souvlaki = { version = "0.7.3", default-features = false, features = [
    "use_zbus",
], optional = true }
thiserror = "1.0.61"
rusty_ytdl = { version = "0.7.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta.22", features = [
    "protocol-asset",
    "devtools",
], optional = true }
serde_json = "1.0"
diesel = { version = "2.2.1", features = [
    "sqlite",
    "r2d2",
    "serde_json",
], optional = true }
json_dotpath = { version = "1.1.0" }
fast_image_resize = { version = "4.0.0", optional = true }
image = { version = "0.25.1", optional = true }
lofty = { version = "0.20.0", optional = true }
jwalk = { version = "0.8.1", optional = true }
librespot = { git = "https://github.com/librespot-org/librespot", branch = "dev", features = [
    "default",
], optional = true }
reqwest = { version = "0.12.4" }
protobuf = { version = "3.4.0", features = ["bytes"], optional = true }
uuid = { version = "1.8.0", features = ["v4"] }
zip = { version = "2.1.3", optional = true }
fs_extra = { version = "1.3.0", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
oauth2 = { version = "4.4.2", optional = true }
rspotify = { version = "0.13.2", optional = true }
async-trait = { version = "0.1.80" }
google-youtube3 = { version = "5.0.5", optional = true, features = [
], default-features = false }
