[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["core"]
core = [
    "dep:souvlaki",
    "dep:rusty_ytdl",
    "dep:tauri",
    "dep:diesel",
    "dep:fast_image_resize",
    "dep:image",
    "dep:lofty",
    "dep:jwalk",
    "dep:librespot",
    "dep:reqwest",
    "dep:protobuf",
    "dep:zip",
    "dep:fs_extra",
]
ui = ["dep:wasm-bindgen", "dep:serde-wasm-bindgen"]

[dependencies]
souvlaki = { version = "0.7.3", default-features = false, features = [
    "use_zbus",
], optional = true }
thiserror = "1.0.57"
rusty_ytdl = { version = "0.6.6", optional = true }
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta", features = [
    "protocol-asset",
    "devtools",
], optional = true }
serde_json = "1.0"
diesel = { version = "2.1.0", features = [
    "sqlite",
    "r2d2",
    "serde_json",
], optional = true }
json_dotpath = { version = "1.1.0" }
fast_image_resize = { version = "3.0.4", optional = true }
image = { version = "0.24.7", optional = true }
lofty = { version = "0.18.2", optional = true }
jwalk = { version = "0.8.1", optional = true }
librespot = { git = "https://github.com/librespot-org/librespot", branch = "dev", features = [
    "default",
], optional = true }
reqwest = { version = "0.11.24", optional = true }
protobuf = { version = "3.3.0", features = ["bytes"], optional = true }
uuid = { version = "1.7.0", features = ["v4"] }
zip = { version = "0.6.6", optional = true }
fs_extra = { version = "1.3.0", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
