[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.57"
rusty_ytdl = "0.6.6"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta", features = ["protocol-asset", "devtools"] }
serde_json = "1.0"
diesel = "2.1.0"
json_dotpath = "1.1.0"
