[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
souvlaki = { version = "0.7.3", default-features = false, features = [
    "use_zbus",
] }
thiserror = "1.0.57"
rusty_ytdl = "0.6.6"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta", features = ["protocol-asset", "devtools"] }
serde_json = "1.0"
diesel = { version = "2.1.0", features = ["sqlite", "r2d2", "serde_json"] }
json_dotpath = "1.1.0"
fast_image_resize = "3.0.4"
image = "0.24.7"
lofty = "0.18.2"
jwalk = "0.8.1"
librespot = { git = "https://github.com/librespot-org/librespot", branch = "dev", features = [
    "default",
] }
reqwest = "0.11.24"
protobuf = { version = "3.3.0", features = ["bytes"] }
uuid = { version = "1.7.0", features = ["v4"] }
