[package]
name = "types"
edition = "2021"
version = "0.1.0"

[dependencies]
serde_json = "1.0"
thiserror = "1.0.63"

[dependencies.async-trait]
version = "0.1.81"
features = []

[dependencies.diesel]
version = "2.2.2"
features = ["r2d2", "32-column-tables", "sqlite", "serde_json"]
optional = true
default-features = false

[dependencies.fast_image_resize]
version = "4.2.1"
features = []
optional = true

[dependencies.fs_extra]
version = "1.3.0"
features = []
optional = true

[dependencies.google-youtube3]
version = "5.0.5"
features = []
optional = true
default-features = false

[dependencies.hex]
version = "0.4.3"
features = []
optional = true

[dependencies.image]
version = "0.25.2"
features = []
optional = true

[dependencies.json_dotpath]
version = "1.1.0"
features = []

[dependencies.jwalk]
version = "0.8.1"
features = []
optional = true

[dependencies.keyring]
version = "2.3.3"
features = []
optional = true

[dependencies.librespot]
git = "https://github.com/librespot-org/librespot"
branch = "dev"
features = ["default"]
optional = true

[dependencies.lofty]
version = "0.20.1"
features = []
optional = true

[dependencies.oauth2]
version = "4.4.2"
features = []
optional = true

[dependencies.protobuf]
version = "3.5.0"
features = ["bytes"]
optional = true

[dependencies.reqwest]
version = "0.12.5"
features = []

[dependencies.rspotify]
version = "0.13.2"
features = []
optional = true

[dependencies.rusty_ytdl]
version = "0.7.3"
features = []
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde-wasm-bindgen]
version = "0.6"
features = []
optional = true

[dependencies.souvlaki]
version = "0.7.3"
features = ["use_zbus"]
optional = true
default-features = false

[dependencies.tauri]
version = "2.0.0-beta.24"
features = ["protocol-asset", "devtools"]
optional = true

[dependencies.uuid]
version = "1.10.0"
features = ["v4"]

[dependencies.wasm-bindgen]
version = "0.2"
features = []
optional = true

[dependencies.zip]
version = "2.1.5"
features = []
optional = true

[features]
core = ["dep:souvlaki", "dep:rusty_ytdl", "dep:tauri", "dep:diesel", "dep:fast_image_resize", "dep:image", "dep:lofty", "dep:jwalk", "dep:librespot", "dep:protobuf", "dep:zip", "dep:fs_extra", "dep:oauth2", "dep:rspotify", "dep:google-youtube3", "dep:hex", "dep:keyring"]
default = ["core"]
ui = ["dep:wasm-bindgen", "dep:serde-wasm-bindgen"]
