[package]
name = "types"
edition = "2021"
version = "0.1.0"

[dependencies]
jsonschema = { version = "0.30.0", optional = true, default-features = false }
serde_json = { version = "1.0" }
thiserror = "2.0.12"
tracing = { version = "0.1.41", default-features = false, features = [
    "attributes",
] }
async-trait = { version = "0.1.88", features = [] }
diesel = { version = "2.2.10", features = [
    "32-column-tables",
    "sqlite",
], optional = true, default-features = false }
fast_image_resize = { version = "5.1.4", features = [], optional = true }
fs_extra = { version = "1.3.0", features = [], optional = true }
google-youtube3 = { version = "6.0.0", features = [
], optional = true, default-features = false }
hex = { version = "0.4.3", optional = true, default-features = false }
image = { version = "0.25.6", optional = true, default-features = false }
json_dotpath = { version = "1.1.0", features = [], optional = true }
jwalk = { version = "0.8.1", features = [], optional = true }
keyring = { version = "3.6.2", features = [], optional = true }
librespot = { git = "https://github.com/librespot-org/librespot", branch = "dev", optional = true, default-features = false }
lofty = { version = "0.22.4", optional = true, default-features = false }
oauth2 = { version = "5.0", optional = true, default-features = false }
protobuf = { version = "3.7.2", optional = true, default-features = false }
reqwest = { version = "0.12.20", default-features = false, optional = true }
rspotify = { version = "0.14.0", features = [
    "client-reqwest",
], optional = true, default-features = false }
rusty_ytdl = { git = "https://github.com/Mithronn/rusty_ytdl", optional = true, default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = { version = "0.6", features = [], optional = true }
tauri = { version = "2.5.1", default-features = false, optional = true }
uuid = { version = "1.17.0", default-features = false, optional = true, features = [
    "v4",
] }
wasm-bindgen = { version = "0.2", optional = true, default-features = false }
zip = { version = "3.0", optional = true, default-features = false }
bitcode = { version = "0.6.6" }
rodio = { git = "https://github.com/RustAudio/rodio", optional = true }
extism-convert = { version = "1.11.1", optional = true }
hls_client = { version = "1.1.0", optional = true, default-features = false }



[target.'cfg(windows)'.dependencies]
libsqlite3-sys = { version = "0.33.0", optional = true, features = ["bundled"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
souvlaki = { version = "0.8.2", features = [
    "use_zbus",
], optional = true, default-features = false }


[features]
ui = ["dep:wasm-bindgen", "dep:serde-wasm-bindgen"]
extensions = ["dep:extism-convert"]
extensions-core = ["dep:extism-convert","dep:zip", "dep:fs_extra", "dep:reqwest", "dep:uuid"]
core = [
    "dep:rusty_ytdl",
    "dep:tauri",
    "dep:diesel",
    "dep:fast_image_resize",
    "dep:image",
    "dep:lofty",
    "dep:jwalk",
    "dep:librespot",
    "dep:protobuf",
    "dep:zip",
    "dep:fs_extra",
    "dep:oauth2",
    "dep:rspotify",
    "dep:google-youtube3",
    "dep:hex",
    "dep:keyring",
    "dep:jsonschema",
    "dep:reqwest",
    "dep:json_dotpath",
    "dep:libsqlite3-sys",
    "dep:extism-convert",
    "dep:uuid",
    "dep:rodio",
    "dep:hls_client"
]
default = ["core"]
librespot = ["dep:librespot", "dep:reqwest", "dep:protobuf"]
