# [build]
# target = "x86_64-unknown-linux-gnu"

# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

# [target.wasm32-unknown-unknown]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.aarch64-linux-android]
linker = "/home/ovenoboyo/Android/Sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"
