[package]
name = "tauri-invoke-proc"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.2.9"
lazy_static = "1.5.0"
once_cell = "1.20.2"
proc-macro2 = "1.0.92"
quote = "1.0.37"
regex = "1.11.1"
serde = "1.0.216"
serde_json = "1.0.133"
syn = "2.0.90"
tracing = "0.1.41"

[lib]
proc-macro = true
