[package]
name = "lyrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
reqwest = "0.11.24"
scraper = "0.18.1"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = "1.36.0"
types = { path = "../types" }
librespot = { path = "../librespot" }
