[package]
name = "lyrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.5"
reqwest = "0.12.5"
scraper = "0.19.1"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = "1.39.2"
types = { path = "../types" }
librespot = { path = "../librespot" }
