[package]
name = "rodio-player"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = { version = "0.19.0", default-features = false, features = [
    "symphonia-all",
] }
types = { path = "../types", default-features = false }
stream-download = "0.7.3"
tracing = { version = "0.1.41", default-features = false }
futures = "0.3.31"
tokio = "1.42.0"
