[package]
name = "rodio-player"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = { git = "https://github.com/RustAudio/rodio", default-features = false, features = [
    "symphonia-all",
] }
types = { path = "../types", default-features = false }
stream-download = "0.15.1"
tracing = { version = "0.1.41", default-features = false }
futures = "0.3.31"
tokio = "1.43.0"
hls_m3u8 = "0.5.0"
