[package]
name = "pref_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
types = { path = "../../src-tauri/types", default-features = false, features = [
    "ui",
] }
[lib]
proc-macro = true
